#ifndef TEST_CONFIG_H
#define TEST_CONFIG_H

#define SN_COAP_DUPLICATION_MAX_MSGS_COUNT  1
#define SN_COAP_MAX_BLOCKWISE_PAYLOAD_SIZE 16
#define ENABLE_RESENDINGS 1
#define SN_COAP_MAX_INCOMING_BLOCK_MESSAGE_SIZE 65535

#endif
