/*
 * Copyright (c) 2015 ARM. All rights reserved.
 */
/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_libnsdl_init(void);
extern void test_libnsdl_create_resource(void);
extern void test_libnsdl_list_resources(void);
extern void test_libnsdl_get_resource(void);
extern void test_libnsdl_set_nsp_address(void);
extern void test_libnsdl_register(void);
extern void test_libnsdl_get_requests_to_resources(void);
extern void test_libnsdl_put_requests_to_resources(void);
extern void test_libnsdl_post_requests_to_resources(void);
extern void test_libnsdl_delete_requests_to_resources(void);
extern void test_libnsdl_create_resource_with_post(void);
extern void test_libnsdl_update_resource_value(void);
extern void test_libnsdl_delete_resource(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "Test.c";
  UnityBegin();
  RUN_TEST(test_libnsdl_init, 90);
  RUN_TEST(test_libnsdl_create_resource, 141);
  RUN_TEST(test_libnsdl_list_resources, 260);
  RUN_TEST(test_libnsdl_get_resource, 283);
  RUN_TEST(test_libnsdl_set_nsp_address, 313);
  RUN_TEST(test_libnsdl_register, 334);
  RUN_TEST(test_libnsdl_get_requests_to_resources, 371);
  RUN_TEST(test_libnsdl_put_requests_to_resources, 412);
  RUN_TEST(test_libnsdl_post_requests_to_resources, 455);
  RUN_TEST(test_libnsdl_delete_requests_to_resources, 499);
  RUN_TEST(test_libnsdl_create_resource_with_post, 543);
  RUN_TEST(test_libnsdl_update_resource_value, 576);
  RUN_TEST(test_libnsdl_delete_resource, 612);

  return (UnityEnd());
}
