/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_libcoap_init(void);
extern void test_libcoap_builder_no_options(void);
extern void test_libcoap_builder_token_and_payload(void);
extern void test_libcoap_builder_short_option(void);
extern void test_libcoap_builder_option_30(void);
extern void test_libcoap_builder_option_300(void);
extern void test_libcoap_builder_option_600(void);
extern void test_libcoap_builder_option_800(void);
extern void test_libcoap_builder_message_with_multiple_options(void);
extern void test_libcoap_parser_parse_message_without_options(void);
extern void test_libcoap_parser_parse_message_with_payload_and_token(void);
extern void test_libcoap_parser_parse_message_with_small_option(void);
extern void test_libcoap_parser_parse_message_with_multiple_options(void);
extern void test_libcoap_negative_build_with_null_pointer(void);
extern void test_libcoap_negative_parse_with_null_pointer(void);
extern void test_libcoap_negative_parse_with_coap_packet_len_null(void);
extern void test_libcoap_negative_parse_with_wrong_coap_packet_len(void);
extern void test_libcoap_negative_parse_with_wrong_coap_version(void);
extern void test_libcoap_negative_parse_malformed_coap(void);
extern void test_libcoap_negative_parse_empty_con(void);
extern void test_libcoap_negative_parse_wrong_code_1(void);
extern void test_libcoap_negative_parse_wrong_code_6(void);
extern void test_libcoap_negative_parse_wrong_code_7(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "Test.c";
  UnityBegin();
  RUN_TEST(test_libcoap_init, 70);
  RUN_TEST(test_libcoap_builder_no_options, 80);
  RUN_TEST(test_libcoap_builder_token_and_payload, 107);
  RUN_TEST(test_libcoap_builder_short_option, 138);
  RUN_TEST(test_libcoap_builder_option_30, 165);
  RUN_TEST(test_libcoap_builder_option_300, 189);
  RUN_TEST(test_libcoap_builder_option_600, 212);
  RUN_TEST(test_libcoap_builder_option_800, 236);
  RUN_TEST(test_libcoap_builder_message_with_multiple_options, 259);
  RUN_TEST(test_libcoap_parser_parse_message_without_options, 297);
  RUN_TEST(test_libcoap_parser_parse_message_with_payload_and_token, 318);
  RUN_TEST(test_libcoap_parser_parse_message_with_small_option, 345);
  RUN_TEST(test_libcoap_parser_parse_message_with_multiple_options, 371);
  RUN_TEST(test_libcoap_negative_build_with_null_pointer, 411);
  RUN_TEST(test_libcoap_negative_parse_with_null_pointer, 432);
  RUN_TEST(test_libcoap_negative_parse_with_coap_packet_len_null, 449);
  RUN_TEST(test_libcoap_negative_parse_with_wrong_coap_packet_len, 463);
  RUN_TEST(test_libcoap_negative_parse_with_wrong_coap_version, 477);
  RUN_TEST(test_libcoap_negative_parse_malformed_coap, 491);
  RUN_TEST(test_libcoap_negative_parse_empty_con, 505);
  RUN_TEST(test_libcoap_negative_parse_wrong_code_1, 520);
  RUN_TEST(test_libcoap_negative_parse_wrong_code_6, 535);
  RUN_TEST(test_libcoap_negative_parse_wrong_code_7, 550);

  return (UnityEnd());
}
